# Generated by Django 4.2.11 on 2024-04-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_report_report_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.TextField(default=''),
        ),
    ]
